# This is a basic workflow to test the source code 
name: Build - Deploy 

# Controls when the action will run. Triggers the workflow on push or pull request

on:
  push:
    branches: [release, develop]
  pull_request:
    branches: [release, develop]

jobs:
# build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup node js
        uses: actions/setup-node@master
        with:
          node-version: '22.x'
      - name: Install dependencies need to build the app
        run: |
          npm install
          npm install @angular-devkit/build-angular 
          
      - name: Build source code
        run: npm run build 
        
      - name: Archive to the dist
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./dist/angular-test/browser

      - name: Init Firebase
        run: npm install -g firebase-tools
        
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
         args: deploy --only hosting
        env:
         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    
